imports:
    - php

tools:
    external_code_coverage:
        timeout: 2100
    # disable copy paste detector and similarity analyzer as they have no real value
    # and a huge bunch of false-positives
    php_sim: false
    php_cpd: false

build:
    environment:
        php:
            version: 7.0

    dependencies:
        before:
            - 'travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0" --no-plugins'
