# faster builds on new travis setup not using sudo
sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

services:
  - mysql

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0" --no-plugins
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  - mysql --version

  # initialize database
  - mysql -e 'CREATE DATABASE `yii2-usuario-test`;';
  - php tests/_app/yii.php migrate/up --interactive=0

script:
  - composer validate --no-check-lock
  - vendor/bin/codecept run

notifications:
  email:
    - resurtm+travis-ci@gmail.com

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
